import type { Question, QuestionInteractionState } from '../types/lesson'
import { subtractTarget } from './validation'
import { add, scale, type Vec2 } from './vectorMath'

/**
 * Build the canonical "correct" interaction state for a question — i.e. the state a learner would be
 * in having answered it perfectly. Used to verify generated/parameterized questions: a question is
 * only safe to serve if `validateQuestion(question, correctStateFor(question))` is true.
 *
 * Returns null for question types whose answer isn't a computed vector/scalar (multiple choice,
 * reachable/recognize verdicts) — those aren't generated by the practice engine.
 */
export function correctStateFor(question: Question): QuestionInteractionState | null {
  switch (question.type) {
    case 'drawVector':
      return { type: 'drawVector', tip: (question.correctAnswer.target ?? [0, 0]) as Vec2 }
    case 'readVector':
      return { type: 'readVector', vectorInput: question.correctAnswer.vector }
    case 'findMagnitude':
      return { type: 'findMagnitude', magnitudeInput: question.correctAnswer.magnitude }
    case 'headToTailFull': {
      const { vectorA, vectorB } = question.correctAnswer
      const sum = add(vectorA, vectorB)
      return { type: 'headToTailFull', vectorA, vectorB, bTail: vectorA, sumTip: sum, sumInput: sum }
    }
    case 'headToTailFree': {
      const { vectorA, vectorB } = question.correctAnswer
      const sum = add(vectorA, vectorB)
      return { type: 'headToTailFree', vectorA, vectorB, bTail: [0, 0], sumTip: [0, 0], sumInput: sum }
    }
    case 'scalarSlider': {
      const { baseVector, scalar } = question.correctAnswer
      return {
        type: 'scalarSlider',
        baseVector,
        scalar,
        vectorInput: scale(baseVector, scalar),
        scalarInput: scalar,
      }
    }
    case 'vectorSubtract': {
      const { vectorA, vectorB } = question.correctAnswer
      return {
        type: 'vectorSubtract',
        vectorA,
        vectorB,
        negDisp: [0, 0],
        negTail: [0, 0],
        sumTip: [0, 0],
        sumInput: subtractTarget(question.correctAnswer),
      }
    }
    case 'constructCombo': {
      const answer = question.correctAnswer
      const isFindScalars = question.mode === 'findScalars'
      return {
        type: 'constructCombo',
        vectorA: answer.vectorA,
        vectorB: answer.vectorB,
        aScale: 0,
        bScale: 0,
        bTail: [0, 0],
        resultTip: [0, 0],
        resultInput: isFindScalars ? [0, 0] : answer.target,
        coefAInput: isFindScalars ? answer.coefA : 0,
        coefBInput: isFindScalars ? answer.coefB : 0,
        reachableInput: null,
      }
    }
    default:
      return null
  }
}
